### ISSUE TITLE
Create an API for interacting with the contracts

### ISSUE THREAD

**Issue by chatch** [chatch/hashed-timelock-contract-ethereum#8]
Create a thin wrapper around truffle-contract generated interface to make interacting with the contracts from javascript easier.

Bundle it to npm ethereum-htlc.

**Comment by danmuf** [comment]
@chatch Is this issue still open and can be resolved by me/us?

**Comment by chatch** [comment]
hi @danmuf yes I think it's still a useful thing to add. If you'd like to submit a pull request for it please feel free.

**Comment by danmuf** [comment]
#16

**Comment by chatch** [comment]
looks great! I've just merged the pull request.

**Comment by chatch** [comment]
Released v0.0.11 to npm : https://www.npmjs.com/package/ethereum-htlc
